fix(ci): add the done stage to act as a ruleset flag

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -81,6 +81,21 @@ jobs:
           tag_name: ${{ needs.release.outputs.release-git-tag }}
           files: ${{ matrix.target }}.tar.gz
 
+  done:
+    needs: [release, artifacts]
+    name: Done
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check for Failed Jobs
+      run: |
+        if [[ "${{ needs.release.result }}" == "failure" || "${{ needs.artifacts.result }}" == "failure" || "${{ needs.multi-arch.result }}" == "failure" ]]; then
+          echo "One or more jobs failed. Marking release as failed."
+          exit 1
+        else
+          echo "All jobs succeeded or were skipped. Marking release as successful."
+        fi
+
   cleanup:
     needs: [release]
     if: failure()
